### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by LuminousRedNova** [Morganmrose/COMP330---Twitter#1]
For documentation, I can read it and am familiar with C#, but for others that aren't I would just add some more descriptive stuff. Even just for little stuff like `private double m_length = 0;` could just be commented on the side as for why you're setting the message length to zero rather that leaving it NULL, or even what `double m_length` is. Also, it might be fun to add, in addition to just a counter, also some way of storing and retrieving the mentions for example.

**Comment by Morganmrose** [comment]
Thank you, I'll be sure to add more descriptions if they'd be more helpful. And I agree with storage options, I would like something more complex yet useful than just the x++ methods in the main.
