### ISSUE TITLE
Sneak Peak

### ISSUE THREAD

**Issue by joehernandez11** [Morganmrose/COMP330---Twitter#3]
I begin reviewing your code and I see this and I kind of want to know what will go in here:
    private Twitter()
        {
        }

a comment could tell the reviewer of what's to come. I am also coding in C# and have trouble figuring out the regex implementation. Anyway don't forget to include some unit test. Some meant to pass and some meant to fail.

**Comment by Morganmrose** [comment]
Thank you, and good idea - I'll comment my ideas as I go. I'm wanting to not rely on the main function to run the tests and will implement other classes. When I get the regex to work, I'll let you know - it's something I definitely want to get to work since they're so useful.
