### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by louiehernandez95** [Morganmrose/COMP330---Twitter#7]
I think you should document your code. I had to reread your code twice to understand what was going on. And in my opinion I think you should have little to nothing in your main class, The main should just be the surface of your program. What you already have in your program you should put in separate classes with descriptive titles. Do not forget to do more unit tests as well! I know this is repetitive but I hope this helped!

**Comment by Morganmrose** [comment]
Yes, I definitely need more unit tests. Thank you for your feedback.
